name: "Unity Build"
description: "Builds projects using the Unity CLI on custom action runners"

inputs:
  unity_path_var:
    description: "Name of the environment variable that contains the path to the Unity executable"
    required: true
  project_path:
    description: "Path to the Unity project to build. Can be relative to the current working directory or absolute"
    required: true
  output_path:
    description: "Path to the output directory. Can be relative to the current working directory or absolute"
    required: true
  platform:
    description: "Platform to build for. Can be one of: StandaloneWindows, StandaloneWindows64, StandaloneLinux64"
    required: true
  execute_method:
    description: "Name of the static editor method which starts the build pipeline"
    required: false
    default: "JNI.Editor.CI.CIBuild.Build"
  il2cpp:
    description: "Whether to use IL2CPP for the build"
    required: false
    default: false
  il2cpp_compiler_config:
    description: "The IL2CPP compiler configuration to use. Can be one of: master, release, debug"
    required: false
    type: choice
    options:
      - master
      - release
      - debug
    default: master

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: "JannikNickel/UnityBuildAction"
        path: "./UnityBuildAction"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.12"

    - name: Install Dependencies
      run: pip install -r ./UnityBuildAction/requirements.txt
      shell: cmd

    - name: Build Project
      env:
        INPUT_UNITY_PATH_VAR: ${{ inputs.UNITY_PATH_VAR }}
        INPUT_PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
        INPUT_OUTPUT_PATH: ${{ inputs.OUTPUT_PATH }}
        INPUT_PLATFORM: ${{ inputs.PLATFORM }}
        INPUT_EXECUTE_METHOD: ${{ inputs.EXECUTE_METHOD }}
        INPUT_IL2CPP: ${{ inputs.IL2CPP }}
        INPUT_IL2CPP_COMPILER_CONFIG: ${{ inputs.IL2CPP_COMPILER_CONFIG }}
      run: python ./UnityBuildAction/builder/build.py
      shell: cmd

    - name: Cleanup
      run: rmdir UnityBuildAction /s /q
      shell: cmd
